### ISSUE TITLE
Copyright status of mascot

### ISSUE THREAD

**Issue by spwhitton** [alphapapa/taxy.el#5]
Hello,

I'm packaging taxy for Debian.  May I ask about the copyright status of the mascot image?  Did you make it yourself?

Thanks.

**Comment by alphapapa** [comment]
Hello,

All of the mascot images on my projects are based on public domain or CC-share-alike-licensed images.

**Comment by spwhitton** [comment]
Thank you for the reply, that's great to hear.  Would it be possible to
have a link to the source of the image you based your work on, please?

I found your .xcf in the meta/mascot branch, which satisfies Debian's
requirements for having all preferred forms for modification, but I need
to document the actual license and copyright of the base image.  Thanks.

-- 
Sean Whitton

**Comment by alphapapa** [comment]
I don't have a link to the original source anymore.  If you search for the `squirrel-portrait.jpg` image file using, e.g. Google Images, you can see that it's present on very many Web sites, and Google Images reports that it's in the public domain.

Other than that, I was careful to only select a suitably licensed image for including in my GPL-licensed project, and I can only offer my word for it now.

**Comment by spwhitton** [comment]
Again, many thanks for looking, I'll drop the image from the Debian packaging given that it's only used for the README.
